### ISSUE TITLE
Undefined elem Si / mass not found for element Si

### ISSUE THREAD

**Issue by anaome** [jvolkening/p5-MS#1]
Hi Jeremy,
I'd like to report a minor issue with the MS::Mass functions. It seems that element "Si" is not recognized...

BW

**Comment by jvolkening** [comment]
Thanks for pointing this out. Unimod is used as the data source for the module, and it appears that Unimod only includes a subset of elements in its mass tables for some reason.

I'll make a note of this in the documentation and find a way to retrieve the full set of elemental masses from a different data source. It looks like PubChem might be a potential candidate.

**Comment by jvolkening** [comment]
Should be fixed by d5a065dc46b6dcea840c1e5e174f1292d4617e9b, which pulls average and monoisotopic mass data from PubChem for elements missing in Unimod. Updated package (v0.206002) will be available on CPAN shortly.
